name: ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: typos-action
        uses: crate-ci/typos@master
        with:
          files: .
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync
      - name: mdlint
        uses: DavidAnson/markdownlint-cli2-action@v9
      - name: Sphinx build
        run: |
          source .venv/bin/activate
          cd docs && make SPHINXOPTS='--color -W' html
